### ISSUE TITLE
Instalation type

### ISSUE THREAD

**Issue by dotevo** [yancharkin/games_nebula#10]
Some "native games" prepared by GOG use old Wine and it should be possible to choose how we want to install the game. (Native/Windows version). It will be nice if in the future app will contain some playonlinux features like a few Wine versions.

**Comment by yancharkin** [comment]
There is no way to find automatically if "native" game is just a wine wrapper. But you can use install script or 'autosetup.ini' to let 'Games Nebula' know that it's a wrapper (check out 'two_worlds' in 'autosetup.ini').  And 'Games Nebula' already has feature you mention.
