### ISSUE TITLE
Provide Flatpak/AppImage package?

### ISSUE THREAD

**Issue by Ezwen** [yancharkin/games_nebula#11]
The process to install games_nebula is at the moment quite complex, especially since it requires lgogdownloader which is also hard to install.

Would you consider in the future to try to provide a Flatpak/AppImage version of games_nebula? This would reduce the packaging effort to a single format, which can then be used in any linux distro. Notably, such Flatpak/AppImage would include lgogdownloader and its dependencies.

**Comment by yancharkin** [comment]
'Games Nebula'  in its current state no more than a quick and dirty solution or a prototype at best. It has a lot of problems and certainly not ready for widespread use. Check out the [roadmap](https://github.com/yancharkin/games_nebula#roadmap). There is a lot of things to do before packaging. But if I ever reach that point I'll consider all popular package formats.

**Comment by Ezwen** [comment]
OK, that's understandable :). Thanks for answering and good luck!
