### ISSUE TITLE
Authorization failed help

### ISSUE THREAD

**Issue by Ultraz46** [yancharkin/games_nebula#12]
Problem in Rekaptcha tell me how to solve the problem ?
What to do in? .config/lgogdownloader/cookies.txt

**Comment by yancharkin** [comment]
Open GOG.COM tab (in 'Games Nebula') and authorize there, cookies will be saved to ~/.config/lgogdownloader/cookies.txt Restart application. It should work now.

**Comment by Ultraz46** [comment]
Did not help error left OS Arch ((
![screenshot_69](https://user-images.githubusercontent.com/34344075/33732703-569a1a6a-db98-11e7-8d93-55f7013698aa.png)
![screenshot_70](https://user-images.githubusercontent.com/34344075/33732779-8ceec156-db98-11e7-947c-26193b23c2da.png)
![screenshot_65](https://user-images.githubusercontent.com/34344075/33732817-b0f21ec2-db98-11e7-8399-383a4ed8f0e8.png)

**Comment by yancharkin** [comment]
Какая версия lgogdownloader?
У меня 3.2.8f55f3a и ошибка в подобной ситуации выглядит по-другому:
![lgogdownlaoder](https://user-images.githubusercontent.com/12972830/33736205-ca8dfa40-dba2-11e7-8d6a-0ddd5b65190a.png)
Описанный мной способ работает, только что проверил (и насколько помню работал и в версии 3.1).

**Comment by Ultraz46** [comment]
Версия 3.3-1 из AUR брал что уже только не делал не могу победить авторизацию ((

**Comment by yancharkin** [comment]
Посмотрел коммиты lgogdownloader - он теперь по другому работает, надо разбираться, сейчас на это нет ни времени ни желания.
Можно попробовать в **games_nebula.py**  в строке 131 заменить **self.goglib_authorized = goglib_check_authorization.goglib_authorized()** на **self.goglib_authorized = True**
А лучше пока установить lgogdownloader 3.2, тогда должно работать по описанному выше способу.

**Comment by Ultraz46** [comment]
Где этот games_nebula.py искать подскажи ?

**Comment by yancharkin** [comment]
В директории программы, там же где и start.sh

**Comment by yancharkin** [comment]
Ещё забыл, если запустится надо нажать кнопку 'Обновить библиотеку' (вверху справа)

**Comment by Ultraz46** [comment]
Проделал эти манипуляции авторизация теперь проходит нормально (ну на деле нет) Библиотека GOG пустая обновление библиотеки не помогает.
В терминале по прежнему пишет:

> Not authorized on GOG
Login form contains reCAPTCHA (https://www.google.com/recaptcha/)
Try to login later
HTTP: Login failed
Login form contains reCAPTCHA (https://www.google.com/recaptcha/)
Try to login later
HTTP: Login failed
Login form contains reCAPTCHA (https://www.google.com/recaptcha/)
Try to login later
HTTP: Login failed
Not authorized on GOG

**Comment by yancharkin** [comment]
Тогда изменения лучше откатить.
Вообще это проблема [lgogdownloader](https://github.com/Sude-/lgogdownloader), если настроишь его автономно, то и в "Games Nebula' должнен работать. Можно попробовать авторизоваться с lgogdownloader напрямую: с разными  опциями --login-api --login-website, может в новой версии какие-то новые появились, в общем по-очереди попробовать все 'login' опции. Но тут я помочь не могу, сам использую 3.2 и пока не вижу причин обновляться. И тебе бы рекомендовал пока использовать эту версию.

**Comment by Ultraz46** [comment]
Проблема еще в том что я не могу найти 3.2 версию что бы попробовать!

**Comment by yancharkin** [comment]
Я крайне редко пользуюсь Arch'ем, но насколько я помнимаю, можно скачать PKGBUILD для lgogdownloader из AUR заменить **pkgver=3.3** на **pkgver=3.2**, собрать и установить пакет как обычно.

**Comment by yancharkin** [comment]
Сегодня скомпилоровал свежий lgogdownloader из git, та же проблема, что и у тебя: не могу залогниться. И похоже способа обойти капчу как можно было в предыдущей версии - нет. 
Написал разработчику, но не факт, что проблема будет решена быстро (или вообще будет решена). Так что пока я вижу один вариант - собирать более старую версию.

**Comment by yancharkin** [comment]
For those who didn't understand Russian: problem emerge if you're using lgogdownloader > 3.2. Looks like login in current versions is broken. To prevent this issue use lgogdownloader 3.2.

**Comment by yancharkin** [comment]
В чём проблема? По-моему установить lgogdownloader 3.2 в Archlinux не так сложно? Даже проще чем во многих других дистрибутивах. Я могу ошибаться в деталях (так как не пользуюсь Arch'ем), но процесс примерно такой: 
1. скачать [lgogdownloader из AUR](https://aur.archlinux.org/cgit/aur.git/snapshot/lgogdownloader.tar.gz)
2. распаковать куда-нубудь
3. перейти в директорию куда распаковал архив 
4. в **PKGBUILD** заменить **pkgver=3.3** на **pkgver=3.2**
5. выполнить **makepkg -cs** в этой директории
6. когда сборка закончиться, установить пакет: **sudo pacman -U lgogdownloader.pkg.tar.xz**

**Comment by ivanpu** [comment]
Проще - так как AUR использует git, то PKGBUILD для версии 3.2 можно взять здесь:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lgogdownloader&id=5651925bd86fdb8a4197c2476fb7a2440b657231

**Comment by Ultraz46** [comment]
Не как я не могу победить Небулу...
Собрал и установил lgogdownloader 3.2 но теперь не запускается вообще ((

**Comment by yancharkin** [comment]
Что в терминале?

**Comment by Ultraz46** [comment]
![2017-12-14 02-20-15](https://user-images.githubusercontent.com/34344075/33967691-8e7055c6-e075-11e7-8b03-608db6a83566.png)

**Comment by Ultraz46** [comment]
Зато теперь работает авторизация 
![2017-12-14 02-23-29](https://user-images.githubusercontent.com/34344075/33967753-da643d58-e075-11e7-9e09-1bb580258b60.png)

**Comment by yancharkin** [comment]
xrandr что выдаёт?

**Comment by Ultraz46** [comment]
xrandr что то вообще не чего не выдает "команда не найдена" пишет!

**Comment by yancharkin** [comment]
Я так понимаю установлен Wayland, не X11. Не знаю как "правильно" обойти эту проблему (может [XWayland](https://wiki.archlinux.org/index.php/Wayland_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)#XWayland) может помочь?)

"Неправильно" - можно удалить или закомментировать 125 строку в **games_nebula.py:**
```
self.get_monitors()
```
 и далее делать так во всех случаях, когда проблема возникает (смотреть нужный файл и строку в выводе терминала).

**Comment by yancharkin** [comment]
Вообще по-идеи, установка пакета **xorg-server-xwayland** дожна помочь.

**Comment by Ultraz46** [comment]
Да вейланд у меня xorg-server-xwayland стоит пакет уже

**Comment by yancharkin** [comment]
Тогда пока по первому варианту - удалять или комментировать строки. Потом посмотрю, как можно правильно сделать.

**Comment by Ultraz46** [comment]
закоментировал все осталась одна проблема такой строки нет...

> File "/home/ultraz/Загрузки/games_nebula_20171113/games_nebula.py", line 6932
    
                         ^
IndentationError: expected an indented block

**Comment by Ultraz46** [comment]
В общем после коментирования все ошибки пропали но не запускается процесс висит и все ((

**Comment by yancharkin** [comment]
Не надо все строки из ошибки комментиповать, в данном случае только 125. В дальнейшим если будет подобная ошибка, комментировать строки в который используется **self.get_monitors()**

**Comment by Ultraz46** [comment]
Ну вот если одну ее коментирую все равно много ошибок вылазит 
![2017-12-14 03-18-32](https://user-images.githubusercontent.com/34344075/33969312-9f287332-e07d-11e7-9765-54b4291663ce.png)

**Comment by yancharkin** [comment]
Всё верно, но так долго комментировать придётся :) Откатывай изменения.
Проблема в том, что не установален xrandr. Я так понимаю, надо установить **xorg-xrandr**
Как раньше запускалось?

**Comment by Ultraz46** [comment]
Раньше стояла SwagArch а теперь Manjaro Gnome

**Comment by Ultraz46** [comment]
xorg-xrandr не хватало и правда ИЗИ все заработало спасибо ))

**Comment by yancharkin** [comment]
Пожалуйста.

**Comment by Ultraz46** [comment]
Еще вопрос если пишет (Невозможно установить) значит не судьба? Так надеялся что гвинт заработает ((

**Comment by yancharkin** [comment]
Нет Gwent не получиться. Он без Galaxy вообще не работает.

**Comment by yancharkin** [comment]
Единственное, что можно попробовать - установить Galaxy в Wine. Но тут я ничем не могу помочь.

**Comment by yancharkin** [comment]
**Summary:** it's a bug in the latest version of lgogdownloader.  Use lgogdownloader 3.2 for now.
