### ISSUE TITLE
Package for AUR

### ISSUE THREAD

**Issue by mwohlert** [yancharkin/games_nebula#13]
Hi I added a package for the aur.
https://aur.archlinux.org/packages/games_nebula/

Maybe you want to add it to the README ;)

**Comment by yancharkin** [comment]
Thanks! README updated.

**Comment by Ultraz46** [comment]
The same authorization error ((

**Comment by mwohlert** [comment]
Yes sure. The script only installs games_nebula. Your package manager will install the dependencies and lgogdownloader will be installed with 3.3, with the broken Galaxy API Login. I commented to the package

**Comment by Ultraz46** [comment]
Add to AUR lgogdownloader version 3.2?

**Comment by mwohlert** [comment]
When you are using arch you shoul be familiar with PKGBuilds, you can do it yourself if you want, but I won't because it does not seem necessary to me

**Comment by yancharkin** [comment]
@mwohlert Using code from "releases" for AUR package never was the best option and now when I'm no longer planning to make them, you should build package using code from master branch (and it makes maintaining it much easier). Also doesn't looks like latest package works well, some users miss message that they have to run setup.sh (issue #33).

I made some change in setup.sh and modified your AUR package: [games_nebula-git.tar.gz](https://github.com/yancharkin/games_nebula/files/2219697/games_nebula-git.tar.gz)
If you have time, please take a look. As far as I can tell it works fine, but I'm not using Arch, so there is a chance I made something incorrectly.
