### ISSUE TITLE
Restructure games_nebula.py

### ISSUE THREAD

**Issue by mwohlert** [yancharkin/games_nebula#14]
Hi,

I really want to contribute to this project, but the games_nebula.py which is the main class I presume is so long and not structured very well. 
Is there a possiblity for you to structure into diffrent files to keep the code inside individual files small?

I'm not a 100% pro with Python, but 5k Lines in one file is pretty hardcore ;)

**Comment by yancharkin** [comment]
I started this project as very simple script (few hundred lines) for downloading and installing games and it was OK to have only one file. Somehow I ended with what we have now. That  was unexpected for me as well :) I'd like to restructure code, it's even on the [roadmap](https://github.com/yancharkin/games_nebula#roadmap). But there is things that stops me:
First, I'm not a coder/programmer so it'll probably take a lot of time and energy. Second and most important, I don't see a good enough reason to do that. If GOG release Galaxy for Linux or change API and lgogdownloader stop working 'Games Nebula' become mostly useless. I don't think that investing too much time in  such project is a good idea. And 'Games Nebula' works OK (most of the time) as it is. So for now I'm not planning to work on this project much. It may change if something important happens, for example if GOG opens API. Still you can contribute by writing installation scripts or translating application.

**Comment by mwohlert** [comment]
This project ist pretty impressive for you not being a coder. 
I see your point in not wanting to invest more time and thats time, but I don't see GOG releasing Galaxy for Linux soon, since that has been the request since 2014 and it's not on their roadmap.
Regarding the API, I do not have any problem with writing a client consuming the api using python. I've done this in many languages already. Even with Sites that don't provide an api.
I'd like to get more into Python, so maybe I'll restructure the code an make a pr.

Thanks for your efforts so far

**Comment by yancharkin** [comment]
Well if you wish you can try :)
Another option I can suggest if you're comfortable with working with API: you can write a replacement for lgogdownloader and it certainly motivate me to work on this project more. This application / module should be able to login even if  login form contains reCAPTCHA or security code, it should have GUI and it should be able to list and download games. If you interested we can discuss it in more details later.

**Comment by yancharkin** [comment]
I started re-writing app from scratch. [More info here](https://github.com/yancharkin/games_nebula/issues/27).
