### ISSUE TITLE
Crashing on launch - python: No such file or directory

### ISSUE THREAD

**Issue by jathanasiou** [yancharkin/games_nebula#15]
I have installed nebula on Manjaro 4.14 kernel with **lgogdownloader v3.2.2** to avoid login issues, however I had the same behaviour occur with 3.3 as well.  
Upon launching the `/opt/games_nebula/games_nebula.py` file with python2 or calling the `start.sh` script I get the below output and the program exits: 

```bash
Traceback (most recent call last):
  File "/opt/games_nebula/games_nebula.py", line 6931, in <module>
    sys.exit(main())
  File "/opt/games_nebula/games_nebula.py", line 6927, in main
    app = GUI()
  File "/opt/games_nebula/games_nebula.py", line 125, in __init__
    self.get_monitors()
  File "/opt/games_nebula/games_nebula.py", line 6567, in get_monitors
    proc = subprocess.Popen(['xrandr'],stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
All of the [required and optional dependencies for Archlinux](https://github.com/yancharkin/games_nebula#archlinux) appear to be properly installed via pacman/AUR.

**Comment by yancharkin** [comment]
'Games Nebula'  use xrandr. You most likely using Wayland not X11, so xrandr not installed on your system. You have to install **xorg-xrandr** and (probably) **xorg-server-xwayland**  if it's not installed.

**Comment by jathanasiou** [comment]
I'm running Cinnamon and I feel rather confident I'm on X.
![screenshot from 2017-12-19 23-29-20](https://user-images.githubusercontent.com/8679925/34179690-99ae625e-e514-11e7-8bb3-47dfbd32e5a5.png)

**Comment by yancharkin** [comment]
Anyway you need **xrandr**, error indicates that it's not installed.

**Comment by jathanasiou** [comment]
It appears that `xorg-xrandr` resolves the issue. If that is required however it probably needs to be added to the dependencies of the [AUR package](https://aur.archlinux.org/packages/games_nebula/), right?

**Comment by yancharkin** [comment]
Looks like it. It's just strange. Usually xrandr installed automatically when using X11.
Also I'm not maintaining AUR package.
