### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by lorendias** [yancharkin/games_nebula#16]
Is this a GUI? Can we get a screenshot in README.md please, thanks :)

**Comment by yancharkin** [comment]
Click 'Show / hide' to see screenshots.

**Comment by lorendias** [comment]
Thank you, may I suggest having one screenshot and the Show / Hide below that to see more.

I noticed nebula has been mentioned as a gog galaxy alternative in comments on the Linus Tech Tips video and I think the visual communication of what it looks like is really important.

Thank You :)

**Comment by yancharkin** [comment]
Is it that hard to click on the spoiler? :)

**Comment by lorendias** [comment]
Sorry for the late reply, I have a lot going on.

Well, it took me 2 or 3 times and I missed it at a glance, until after this bug report I had never seen a screenshot of the application and I couldn't tell if it was a terminal app, so I figured I would communicate my situation in the hopes of increasing exposure for you and the project.

You may see it differently or disagree, either way good luck and thanks for the cool app.
