### ISSUE TITLE
only able to run as root

### ISSUE THREAD

**Issue by gitdwarf** [yancharkin/games_nebula#18]
wont run as USER, only as ROOT

As root, the script will run and prompts me for my gog login details

As user though - I get the following:
$ ./start.sh
Authorized on GOG
Traceback (most recent call last):
  File "<path to games nebula>/games_nebula_20171113/games_nebula.py", line 6931, in <module>
    sys.exit(main())
  File "<path to games nebula>/games_nebula_20171113/games_nebula.py", line 6927, in main
    app = GUI()
  File "<path to games nebula>/games_nebula_20171113/games_nebula.py", line 165, in __init__
    self.create_main_window()
  File "<path to games nebula>/games_nebula_20171113/games_nebula.py", line 281, in create_main_window
    workarea_width, workarea_height = self.get_monitor_workarea(self.main_window)
  File "<path to games nebula>/games_nebula_20171113/games_nebula.py", line 6641, in get_monitor_workarea
    x = window.get_position().root_x
AttributeError: 'tuple' object has no attribute 'root_x'

**Comment by yancharkin** [comment]
You shouldn't run 'Games Nebula' as root. Where you put it? Do you have write permissions to that directory?

**Comment by gitdwarf** [comment]
the location (and files) are fully user readable (and writable)
(has user as the owner too even)

**Comment by yancharkin** [comment]
What distro are you using?

**Comment by gitdwarf** [comment]
Slackware64 (variant)

**Comment by yancharkin** [comment]
Try to comment or remove lines 282-284 in games_nebula.py

**Comment by gitdwarf** [comment]
That seems to partially work
(though did you mean lines: 281-283?  284 is a blank line)

Now it does the following:
$ ./start.sh 
Authorized on GOG
Getting game names (number) number / number
Getting game info number / number

And then seems to hang
A (non-interactable) black box appears (where the games-nebula 'eyes' would be), but nothing more than that

**Comment by gitdwarf** [comment]
re-ran start.sh
now the "launching 'Games Nebula'" eye appears where the non-interactable black box was - but still hangs after showing

Authorized on GOG

in the console

**Comment by yancharkin** [comment]
If you run in terminal:

    lgogdownloader --list-details
Does it works?
What version of lgogdownloader are you using? (versions > 3.2 may have problems)

**Comment by gitdwarf** [comment]
lgogdownloader: version 3.3

works fine

should I try rolling back lgogdownloader to v3.2 and see if games nebula works then?

**Comment by yancharkin** [comment]
Worth a try.

**Comment by gitdwarf** [comment]
ok, that didnt help
with lgogdownloader 3.2
games nebula, instead of hanging after being authorized with gog
now it crashes - with this in the console

***snipped lots of repeats of the (games_nebula.py:23074): Gtk-CRITICAL **: gtk_container_remove: assertion 'gtk_widget_get_parent (widget) == GTK_WIDGET (container) || GTK_IS_ASSISTANT (container) || GTK_IS_ACTION_BAR (container)' failed***

(games_nebula.py:23074): Gtk-CRITICAL **: gtk_container_remove: assertion 'gtk_widget_get_parent (widget) == GTK_WIDGET (container) || GTK_IS_ASSISTANT (container) || GTK_IS_ACTION_BAR (container)' failed
Traceback (most recent call last):
  File "-path_to_games_nebula-/games_nebula_20171113/games_nebula.py", line 6931, in <module>
    sys.exit(main())
  File "-path_to_games_nebula-/games_nebula_20171113/games_nebula.py", line 6927, in main
    app = GUI()
  File "-path_to_games_nebula-/games_nebula_20171113/games_nebula.py", line 165, in __init__
    self.create_main_window()
  File "-path_to_games_nebula-/games_nebula_20171113/games_nebula.py", line 352, in create_main_window
    self.create_settings_tab()
  File "-path_to_games_nebula-/games_nebula_20171113/games_nebula.py", line 1434, in create_settings_tab
    self.switch_goglib_tab_at_start.connect('state-set', self.cb_switch_goglib_tab_at_start)
TypeError: <Switch object at 0x7f045fa08870 (GtkSwitch at 0xa4b570)>: unknown signal name: state-set

**Comment by gitdwarf** [comment]
tested again with both lgogdownloader 3.2 and 3.3 (flushed config for both lgogdownloader and games nebula)
the above crash situation occurs with both versions

**Comment by yancharkin** [comment]
What version of gtk3 you have on your system?

**Comment by gitdwarf** [comment]
gtk1: 1.2.10
gtk2: 2.24.13
gtk3: 3.12.2

**Comment by yancharkin** [comment]
gtk3 outdated, that the root of all problems. Update it. Also don't forget to revert changes made in 'games_nebula.py'.

**Comment by yancharkin** [comment]
I assume the problem resolved or doesn't matter anymore. Closing the issue.
It's a mystery to me why @gitdwarf have to run 'Games Nebula' as root (there is no need for it). One thing is sure, you need more or less recent gtk3 to use the application.
