### ISSUE TITLE
Escape Credentials

### ISSUE THREAD

**Issue by Nagru** [yancharkin/games_nebula#19]
```
os.system('lgogdownloader --login-email ' + email
+ ' --login-password ' + password)
```

Heads-up that with this code, having certain special characters in the password (such as the brackets around this text) can cause a syntax error. I'd recommend wrapping the password variable in quotations for a quick fix or escaping special characters in passwords for a long-term fix.

**Comment by yancharkin** [comment]
I'm working on a new authorization method. It should be ready soon. But thanks for the tip anyway.

**Comment by Nagru** [comment]
Good to know. Thanks for the hard work!
