### ISSUE TITLE
Freezing at "Launching 'Games Nebula'"

### ISSUE THREAD

**Issue by F-TD5X** [yancharkin/games_nebula#25]
First Time run terminal:
```bash
Gtk-Message: 16:59:06.826: GtkDialog mapped without a transient parent. This is discouraged.

(pygogauth.py:29651): GLib-GIO-CRITICAL **: 16:59:09.710: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(gst-plugin-scanner:29692): GStreamer-WARNING **: 16:59:11.875: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstlv2.so': liblilv-0.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:29692): GStreamer-WARNING **: 16:59:12.068: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstzbar.so': libzbar.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:29692): GStreamer-WARNING **: 16:59:12.222: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstopencv.so': libopencv_bgsegm.so.3.4: cannot open shared object file: No such file or directory
Authorization successful!
Authorized on GOG

```

Second ... : 
```bash
Authorized on GOG
```

And both freezed at "Launching 'Games Nebula'"

**Comment by yancharkin** [comment]
@F-TD5X Your distro?

**Comment by yancharkin** [comment]
@F-TD5X and gtk3 version?

**Comment by F-TD5X** [comment]
@yancharkin 
Sorry for delay.
Archlinux and gtk3 3.22.30

**Comment by yancharkin** [comment]
Are you using AUR package or install everything yourself?
Make sure all dependencies installed and lgogdownloader works as standalone app (for example, try lgogdownloader --list).

**Comment by yancharkin** [comment]
@F-TD5X In particular, make sure python3-pytz and python3-requests (or python2-pytz and python2-requests, depends on you python version) installed.

**Comment by F-TD5X** [comment]
I'm surely they are installed, but this problem still happened.
I can see the launching logo, but nothing after it.

**Comment by yancharkin** [comment]
@F-TD5X Are you using AUR package or not?

What's the output of: 

    lgogdownloader --list

**Comment by yancharkin** [comment]
@F-TD5X After looking closely, I saw:

    (pygogauth.py:29651): GLib-GIO-CRITICAL **: 16:59:09.710: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

Looks like you have some issues with dbus.

After quick googling I can suggest you to look for solution here:
https://wiki.archlinux.org/index.php/D-Bus
https://bbs.archlinux.org/viewtopic.php?id=224640

**Comment by yancharkin** [comment]
@F-TD5X Make sure you have read all my previous messages and provide all information I asked for. Also (cause you replying not very often) I'd like to ask in advance: what DM, DE and/or WM are you using?

**Comment by F-TD5X** [comment]
I am using aur package. i3wm. 

`lgogdownloader --list`  showed 
```
SSL connect error
Failed to get login token
```

**Comment by yancharkin** [comment]
This is the problem:

>     SSL connect error
>     Failed to get login token
Current version of GN for most features use [lgogdownloader](https://github.com/Sude-/lgogdownloader). Try to remove files from ~/.config/lgogdownloader and use lgogdownloader directly. If it doesn't work properly then there is nothing can be done and this issue have nothing to do with GN (except for not showing error message) - it's a problem with lgogdownloader.

**Comment by yancharkin** [comment]
@F-TD5X Have you had a chance to try my latest suggestion?
I almost sure this is not a GN issue, most likely something wrong with your lgogdownloader installation, network or distro configuration (maybe try some other disro in VM?), but I'd like to be sure, because I'm planing to make a new release soon (much needed bugfixes).

**Comment by yancharkin** [comment]
@F-TD5X Is it that hard to reply? "I didn't had a chance to try it", will suffice.

**Comment by F-TD5X** [comment]
I have did something wrong on my system and I have to restore it.
And at now I suffered another issue.
I am sorry, but I can't reply you anything till I meet this issue again.
Maybe this issue can be closed.
