### ISSUE TITLE
Please consider adding support for beta channels

### ISSUE THREAD

**Issue by josch** [yancharkin/games_nebula#26]
In the GOG Galaxy client you can go to the game in your GOG Galaxy library --> More --> Settings. Then toggle BETA CHANNELS to ON. Now, Channel --> Add private channel and then insert a code to get access to playing a beta of a game. This is for example currently possible with Stardew Valley. It would be great if this was also possible with games nebula. Thanks! :-)

**Comment by yancharkin** [comment]
Games Nebula is an unofficial client, I (obviously) don't have same possibilities as Galaxy's developers have. At the moment implementing this feature is absolutely impossible. Not because I don't want, but because I can't. It may change in the future, but I highly doubt it.

**Comment by josch** [comment]
How did you figure out the existing part of the GOG API? I thought I could look into what the official GOG client does and see if I can find out how it does this "beta channel" stuff. But I guess you've already done a lot of this reverse engineering part so that I would not have to start from zero?

**Comment by yancharkin** [comment]
In fact, it's not me who did reverse engineering. Current version of Games Nebula use mostly [lgogdownloader](https://github.com/Sude-/lgogdownloader) and a bit of [pygogapi](https://github.com/Yepoleb/pygogapi). At the moment I'm slowly working on a new version, which will use pygogapi only. Both projects have published some valuable info about GOG API. [Look here](https://gogapidocs.readthedocs.io/en/latest/). I didn't dig into it too deep, but at a first glance there is no way to access "beta channel" (yet?).

**Comment by josch** [comment]
Ah, I see. In that case, there's really nothing you can do about this issue as you have to wait for beta channel support in pygogapi. Thanks for the pointers!

**Comment by yancharkin** [comment]
You are welcome :)

**Comment by yancharkin** [comment]
@josch Closing this issue for now. Feel free to contact me if you'll find a way to implement this feature.
