### ISSUE TITLE
Possible issue with using numerical option values for lgogdownloader

### ISSUE THREAD

**Issue by Sude-** [yancharkin/games_nebula#28]
Games Nebula is currently using numerical option values for lgogdownloader's include, exclude, language and platform options.
I'm planning on dropping cover download support from lgogdownloader and changing some of the numerical values for options in the process which could cause issues for Games Nebula.
Games Nebula should use string values for those options. Especially for include and exclude options.

https://github.com/yancharkin/games_nebula/blob/cd16c2fa05bed2e71cf965138116bbe7bfe6351f/modules/goglib_get_games_list.py#L11-L12
Should be ```'--exclude', 'all'```

https://github.com/yancharkin/games_nebula/blob/cd16c2fa05bed2e71cf965138116bbe7bfe6351f/games_nebula.py#L369
```'--exclude', 'all'```

https://github.com/yancharkin/games_nebula/blob/cd16c2fa05bed2e71cf965138116bbe7bfe6351f/games_nebula.py#L4884-L4886
```'--platform', 'linux,windows'```
```'--language', self.preferred_language + ',en,'```
```'--exclude', 'extras,patches,covers'```

https://github.com/yancharkin/games_nebula/blob/cd16c2fa05bed2e71cf965138116bbe7bfe6351f/games_nebula.py#L4888-L4890
```'--platform', 'linux,windows'```
```'--language', self.preferred_language + ',en,'```
```'--exclude', 'patches,covers'```

I see that you are dropping lgogdownloader in the upcoming version (#27) so this isn't going to be a big issue but until that happens it can cause issues.

**Comment by yancharkin** [comment]
@Sude- Thanks for letting me know; I'll make at least one new release (probably much more), before switching to new version, so it's important info.
