### ISSUE TITLE
Instant crash on startup

### ISSUE THREAD

**Issue by rehtlaw** [yancharkin/games_nebula#29]
first off:
  OS: Arch Linux (not using the AUR package)
  GTK3 Version: 3.22.30

when I try and launch the program, I can see some sort of splash/loading image for a split second, and then get this traceback:
```
Traceback (most recent call last):
  File "/home/jonas/Downloads/games_nebula/games_nebula.py", line 6679, in <module>
    sys.exit(main())
  File "/home/jonas/Downloads/games_nebula/games_nebula.py", line 6675, in main
    app = GUI()
  File "/home/jonas/Downloads/games_nebula/games_nebula.py", line 128, in __init__
    self.monitors_list, self.monitor_primary = monitors.get_monitors()
  File "/home/jonas/Downloads/games_nebula/modules/monitors.py", line 45, in get_monitors
    if re.compile(r'\b({0})\b'.format('connected'), flags=re.IGNORECASE).search(line):
TypeError: cannot use a string pattern on a bytes-like object
```
going by the stacktrace, I'm guessing it has something to do with finding the primary monitor (I run a 2 monitor setup).

**Comment by yancharkin** [comment]
This bug is fixed in master. You can download master or replace:

      if re.compile(r'\b({0})\b'.format('connected'), flags=re.IGNORECASE).search(line):
to

    if re.compile(r'\b({0})\b'.format('connected'), flags=re.IGNORECASE).search(str(line)):

in "/home/jonas/Downloads/games_nebula/modules/monitors.py", line 45

**Comment by rehtlaw** [comment]
OK, I replaced the montiors.py file which fixed the issue. I found out that I still needed to install everything from the AUR (aka htmlcxx and lgogdownloader), but after that, it launches fine. Thanks :)
