### ISSUE TITLE
Won't authorize if install path contains spaces

### ISSUE THREAD

**Issue by Lrss** [yancharkin/games_nebula#30]
Not a huge issue, but still worth noting.

**Comment by yancharkin** [comment]
@Lrss Are you using latest release or master?

**Comment by Lrss** [comment]
Latest release: games_nebula_20180424
on fresh Ubuntu 18.04 installation, unpacked to /opt/games nebula/ and complained during the gog authorization process, but worked fine when renamed to /opt/games-nebula/

**Comment by yancharkin** [comment]
I think this issue fixed in master. You can try it.
Or you can replace

    os.system(sys.executable + ' ' + nebula_dir + '/pygogauth.py')
to

    subprocess.call([sys.executable, nebula_dir + '/pygogauth.py'])

on line 240 in games_nebula.py

**Comment by yancharkin** [comment]
@Lrss This issue is fixed in the latest release. Also from now on it's recommended to use master (until stated otherwise).
