### ISSUE TITLE
Unable to download games

### ISSUE THREAD

**Issue by murtoM** [yancharkin/games_nebula#31]
**System:**
 - Distro: Debian Sid (kernel 4.16.0)
 - gtk3 version: 3.22.30
 - python version: 3.6.5
 - lgogdownloader version: 3.3
 - DE or WM: AwesomeWM
 - DM: None (startx)

**Bug description**
Trying to download any game from the GOG Library does add the game to the download queue, but the download doesn't progress at all. It gives the following output:

```
Traceback (most recent call last):
  File "/home/markus/git/games_nebula/games_nebula.py", line 3031, in update_goglib_interface
    self.goglib_download_game(goglib_installation_queue[0])
  File "/home/markus/git/games_nebula/games_nebula.py", line 4874, in goglib_download_game
    self.preferred_language = self.lang_index[self.goglib_lang]
KeyError: 'English'
```

**Steps to reproduce the behavior**
1. Do the initial setup (installing dependencies, runnig `setup.sh` etc.)
2. Run the app via `start.sh` and login to get your GOG Library
3. Try to download a game in the library via clicking the 'Install' button.
4. Download doesn't progress and you get the output mentioned above.

**Additional info**
The terminal output seems to mention language. If the information helps, my LANG is `en_GB.UTF-8`.

If the problem is in my system, what would you recommend me to do to fix it?

**Comment by yancharkin** [comment]
Open ~/.games_nebula/config/config.ini, it has section called 'gog languages', if languages names started with capital letters just remove this section, if not - let me know I'll try to fix this issue another way.

**Comment by yancharkin** [comment]
My previous comment most likely not useful :)
I pushed fix (hopefully) to master, try it.

**Comment by murtoM** [comment]
Pulled the master and downloading works now! Thank you for your work (:
