### ISSUE TITLE
Can't install Gwent

### ISSUE THREAD

**Issue by klmmmv** [yancharkin/games_nebula#32]
**System:**
 - Distro: Debian Testing
 - python version: 2.7
 - lgogdownloader version: 3.3
 - DE or WM: GNOME
 - DM: gd3

**Bug description**
```bash
2018-Jul-05 10:39:39 [Thread #0] Begin download: setup_gwent_1.2.44.30_en-US.exe
#0 setup_gwent_1.2.44.30_en-US.exe

#0 setup_gwent_1.2.44.30_en-US.exe

#0 setup_gwent_1.2.44.30_en-US.exe

#0 setup_gwent_1.2.44.30_en-US.exe

#0 setup_gwent_1.2.44.30_en-US.exe

2018-Jul-05 10:39:40 [Thread #0] Download complete: setup_gwent_1.2.44.30_en-US.exe (@ 0.00kB/s)
2018-Jul-05 10:39:40 [Thread #0] Finished all tasks
#0: Finished
Traceback (most recent call last):
  File "/home/valentin/Programs/games_nebula/games_nebula.py", line 5479, in watch_process
    self.goglib_install_game(game_name)
  File "/home/valentin/Programs/games_nebula/games_nebula.py", line 5196, in goglib_install_game
    tmp_root_files = os.listdir(tmp_root_path)
OSError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/valentin/.games_nebula/games/goglib/installed/gwent_the_witcher_card_game/game/'
```

**Steps to reproduce the behavior**
- Install games nebula
- Click "install" of any game

**Additional Infor**
Tested Windows games: Gwent Card Game, Tyrian 2000
Didn't have other Windows games

**Comment by yancharkin** [comment]
Thanks for report.
Gwent can't be installed (and played) without Galaxy client. 
Until recently Games Nebula showed warning message about it, but GOG added "offline installer" for the game (which in fact is not a real Gwent installer, try to run in wine), which broke this feature. On the other hand, now Gwent can be installed (probably), which wasn't possible before. I'll try to write a script for it.

**Comment by yancharkin** [comment]
Also the error you have indicates that you have some other issues. Are you sure innoextract (or wine + innounp.exe) installed?

**Comment by klmmmv** [comment]
I have innoextract installed, version 1.6. Thanks for the comments.

**Comment by yancharkin** [comment]
It's strange that '/home/valentin/.games_nebula/games/goglib/installed/gwent_the_witcher_card_game/game/' doesn't exists. Try to use latest [innoextract release](https://github.com/dscharrer/innoextract/releases/tag/1.7): 
- download innoextract-1.7-linux.tar.xz (it's binary release, no need to compile it)
- extract it
- copy innoextract binary from "<extracted_dir>/bin/<yours_cpu_architecture>/innoextract" to 
"/home/valentin/Programs/games_nebula/bin/"

**Comment by klmmmv** [comment]
I did that. 
Same errors again. 
I only tried "tyrian 2000", as Gwent isn't able to be installed so far if I understand you correctly.
Additional information: 
my ~/.games_nebula/games/goglib/downloads directory now contains the directory for tyrian2000 with the downloaded setup.exe for the game. But in the ~/.games_nebula/games/goglib/installed directory, I only have an empty tyrian2000 directory:

```bash
├── downloads
│   ├── devil_daggers
│   ├── gwent_the_witcher_card_game
│   ├── hotline_miami_2_wrong_number
│   ├── jotun
│   └── tyrian_2000
└── installed
    ├── devil_daggers
    │   ├── docs
    │   ├── game
    │   └── support
    ├── hotline_miami_2_wrong_number
    │   ├── docs
    │   ├── game
    │   └── support
    ├── jotun
    │   ├── docs
    │   ├── game
    │   └── support
    └── tyrian_2000
```

**Comment by yancharkin** [comment]
Yes, Gwent can't be installed at the moment, I'm working on it.
Is there anything else in "/home/valentin/Programs/games_nebula/bin/" directory?

**Comment by klmmmv** [comment]
Only ``innounp.exe`` besides an exectuable script ``innoextract``.
Thanks for the effort.

**Comment by yancharkin** [comment]
Try to remove innounp.exe

**Comment by klmmmv** [comment]
Tyrian 2000 works now :+1: 
Thanks for the help.

**Comment by yancharkin** [comment]
That's great. I'll fix setup script: automatic innounp.exe download isn't such a great idea :)
Also I'm writing install script for Gwent right now, so let this issues stay open.

**Comment by yancharkin** [comment]
@klmmmv Here is script for Gwent: [gwent_the_witcher_card_game.zip](https://github.com/yancharkin/games_nebula/files/2167547/gwent_the_witcher_card_game.zip)
Unpack and put directory from archive either to ''/home/valentin/Programs/games_nebula/scripts/goglib/' or to "/home/valentin/.games_nebula/scripts/goglib/"
Using this script and **latest wine-staging (3.11)** I have successfully download, install and launch Gwent.
Unfortunately game unplayable for me: everything is red. I'm using  Nvidia card and proprietary driver. But maybe you'll have a better luck. If you'll decided to give it a try, please let me know the result.

**Comment by yancharkin** [comment]
Also you have to check 'Use own wine prefix' in launcher.

**Comment by yancharkin** [comment]
This script works (sort of), so I added it to scripts repository.

**Comment by klmmmv** [comment]
Thanks. It works for me now. No visual bugs.
