### ISSUE TITLE
Unable to "authorize" (login) to gog.com via Nebula interface

### ISSUE THREAD

**Issue by 0xjon0** [yancharkin/games_nebula#33]
**System:**
 - Distro: Mint 19 - fresh install, and fresh install of Nebula
**Bug description**
Unable to "authorize" (login) to gog.com via Nebula interface
**Steps to reproduce the behavior**
Install dependencies > Install Neblua > launch Nebula > Authorize

I tried to also disable 2FA on gog.com but I still can't login via Nebula.  I use the correct password and it just never lets me login.  However if I load up the GOG.COM tab and login from there, then it works.

**Comment by 0xjon0** [comment]
Also a suggestion: I don't see any indication that a file is being downloaded when I right-click>SaveLinkAs.  The file does download, but it is a bit mysterious and you have to go look in your filesystem to see.

**Comment by yancharkin** [comment]
In the current version of Games Nebula authorization implemented in a very hacky way. For the most features Games Nebula uses lgogdownloader, try to authorize using it directly:

    lgogdownloader --login

**What version of lgogdownloader are you using?**

GOG.COM tab not meant for downloading games, it's something like STORE page in Steam client. Not disabled context menu is a bug not a feature :)

**Comment by yancharkin** [comment]
@tainium ?

**Comment by Fisto69** [comment]
so i had this problem after just setting up the program, after solving it Nebula began to imemdiately crash upon opening. 

running it in terminal gives me this information.


[joshua@JALPC ~]$ games_nebula
Authorized on GOG
Traceback (most recent call last):
  File "/opt/games_nebula/games_nebula.py", line 6747, in <module>
    sys.exit(main())
  File "/opt/games_nebula/games_nebula.py", line 6743, in main
    app = GUI()
  File "/opt/games_nebula/games_nebula.py", line 133, in __init__
    self.create_main_window()
  File "/opt/games_nebula/games_nebula.py", line 335, in create_main_window
    self.create_mylib_tab()
  File "/opt/games_nebula/games_nebula.py", line 864, in create_mylib_tab
    self.mylib_list_titles  = mylib_get_data.games_info(data_dir)
  File "/opt/games_nebula/modules/mylib_get_data.py", line 14, in games_info
    games_list_1 = os.listdir(mylib_dir_1)
OSError: [Errno 2] No such file or directory: '/opt/games_nebula/scripts/mylib'
[joshua@JALPC ~]$ 


i can not figure out how to solve it, and searching shows no results for this problem.

**Comment by yancharkin** [comment]
@Fisto69 
1. You had the same problem as @tainium? How did you solve it?
2. Did you run **setup.sh** script? If you don't have write permissions on **/opt/game_nebula**, you have to run it as root **OR** change permissions **OR** put **games_nebula** somewhere else..

**Comment by Fisto69** [comment]
no, i didnt run setup.sh or anything,  i simply installed from the AUR.  

and when the authorize prompt didn't work i ran the command as you stated above "lgogdownloader --login" to login.

now Nebula simply wont run, it pops open the splash screen for a few seconds than the program kills itself. 

and i cant change the program permissions because all the options are greyed out.    ill try moving it, but perhaps the install process shouldn't put the folder somewhere it cant be accessed from?  


edit: and i cant move it, just copy it.   so the program is useless until its fixed.     ive never had a program install to somewhere where it would be unable to operate from before, this is so ridiculous its actually funny. 

kinda seems like something that should've been caught before it was pushed out to the public?...

**Comment by yancharkin** [comment]
@Fisto69 As you know (you read README before reporting the issue, right?), package in AUR is unofficial, it's maintained by a different person, I can't guarantee that it work. Also 'Games Nebula' in a prototype stage, I never promoted it as ready to use software and never published it outside Github.

**Comment by Fisto69** [comment]
ah well, thats that than i guess.    

i just would've thought there would be ways to request a takedown of your software someone else is uploading if its not actually working since it reflects poorly on you. 


thanks for the help anyway.  hopefully it gets fixed/working soon.

**Comment by yancharkin** [comment]
@Fisto69 Actually, if you're installing package from AUR, there is a message that you have to run setup.sh :0 But anyway there is a number of issues with AUR package, I reported to maintainer. You have a few options: you can wait when maintainer will update the package, you can install app using official instruction in README or you can download this archive: [games_nebula-git.tar.gz](https://github.com/yancharkin/games_nebula/files/2219697/games_nebula-git.tar.gz) and build and install package as you normally build and install packages from AUR. You can report problems with AUR package in issue #13 or on [AUR page](https://aur.archlinux.org/packages/games_nebula/).

@tainium Authorization failed for the same reason (most likely): if you didn't run setup.sh there is no essential GN components on your system and application can't run properly. Another possibility is that something wrong with your lgogdownloader installation (see my first response).

**Comment by yancharkin** [comment]
**Summary:**
- make sure that you have run 'setup.sh'. If there is no 'gogapi' directory in app root, then you didn't do it or something went wrong
- if GN still works incorrectly, make sure lgogdownloader installed and works properly, you can do this by executing lgogdownloader command in terminal
