### ISSUE TITLE
Mint installation

### ISSUE THREAD

**Issue by pinturic** [yancharkin/games_nebula#34]
On mint I received the following error upon launching:

```
nebula ValueError: Namespace WebKit2 not available
```

To solve it I had to add the gir1.2-webkit2-4.0 package with the following command:

```
sudo apt-get install gir1.2-webkit2-4.0
```

---

**System:**
 - Distro: [Mint]
 - gtk3 version: [ 3.18.9]
 - python version [2.7]
 - lgogdownloader version [2.26]
 - innoextract version [1.5]
 - DE or WM [mate]

**Comment by yancharkin** [comment]
Thanks for the report, I'll add this info to the README. Does app work fine now?

**Comment by pinturic** [comment]
Like a charm!!!

**Comment by yancharkin** [comment]
Great!
README updated.
