### ISSUE TITLE
Doesn't start, nothing happens.

### ISSUE THREAD

**Issue by michaelothing** [yancharkin/games_nebula#35]
**ATTENTION!** *Installation instruction in README is the only supported way of GN installation, I do not provide any distro-specific packages. If you installed the application using another way (AUR for example), try re-install using instruction before reporting a bug!*

---

**System:**
 - Distro: Antergos, Arch Based
 - gtk3 version: 3.24
 - python version: 3.7
 - lgogdownloader version 3.4
 - innoextract version 1.7
 - DE or WM Gnome
 - DM  LightDM

**Bug description**
... Nothing happens when starting the program. Tried AUR version first and it showed the splash, then nothing. Then uninstalled and installed according to the Readme, now nothing happens when clicking on the program. Is there a way I can get you a log or something? I have tried to start the program from commandline to get the output, but, haven't figured out how yet.

**Steps to reproduce the behavior**
...

**Screenshots**
(If applicable)

**Additional info**
...

**Comment by yancharkin** [comment]
You can run it from command line by executing

    start.sh
or

    python games_nebula.py
in application root directory.

Also you can try package from here: https://github.com/yancharkin/games_nebula/issues/13#issuecomment-407082461

**Comment by michaelothing** [comment]
This is what happens when I try to start with the python command.
```

Traceback (most recent call last):
  File "games_nebula.py", line 33, in <module>
    from modules import mylib_create_banner, mylib_get_data, mylib_tags_create, mylib_tags_get_all, \
  File "/data/Games/GOG/games_nebula-master/modules/mylib_create_banner.py", line 2, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'
```
I did notice when installing the dependencies the package python3-pytz says it does not exist.

**Comment by michaelothing** [comment]
This is what happens when I try to start with the python command.
```

Traceback (most recent call last):
  File "games_nebula.py", line 33, in <module>
    from modules import mylib_create_banner, mylib_get_data, mylib_tags_create, mylib_tags_get_all, \
  File "/data/Games/GOG/games_nebula-master/modules/mylib_create_banner.py", line 2, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'
```
I did notice when installing the dependencies the package python3-pytz says it does not exist.

**Comment by michaelothing** [comment]
Uhm there is no uninstall script. How can I uninstall the main version in order to install the git version that I made? Sorry if this is a dumb question. I selected make a launcher, so now there is already an icon and that is what tries to open I think after install the one you linked.

**Comment by yancharkin** [comment]
Just remove **~/.local/share/applications/games_nebula.desktop** using your file manager or by executing:

    rm ~/.local/share/applications/games_nebula.desktop

**Comment by yancharkin** [comment]
I'm not using Archlinux, but looks like **python3-pytz** now called **python-pytz**.
As for error, you have to install **python-pillow** package.

**Comment by michaelothing** [comment]
I installed via the pkguild, but, I suspect that the python-pillow dependency was the cause of my headache. It now starts correctly. I wonder why it didn't install before. I copy pasted the code into terminal. Oh well.
