### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by andrewschott** [yancharkin/games_nebula#38]
I did a git clone on the repository and the installation goes well (or so it appears, no errors).

But when running the start.sh script the code chunk below occurs.  Any tips on getting past this?  I did try modifying the script to force python2 & 3 to see if that may have been the issue.  No luck there.

Thanks

> [andrew@schotty-tower-wired games_nebula]$ ./start.sh 
> Authorized on GOG
> Traceback (most recent call last):
>   File "/home/andrew/Applications/GamesNebula/games_nebula/games_nebula.py", line 6751, in <module>
>     sys.exit(main())
>   File "/home/andrew/Applications/GamesNebula/games_nebula/games_nebula.py", line 6747, in main
    app = GUI()
>   File "/home/andrew/Applications/GamesNebula/games_nebula/games_nebula.py", line 137, in __init__
    self.create_main_window()
>   File "/home/andrew/Applications/GamesNebula/games_nebula/games_nebula.py", line 336, in create_main_window
    self.create_goglib_tab_content('auto')
>   File "/home/andrew/Applications/GamesNebula/games_nebula/games_nebula.py", line 525, in create_goglib_tab_content
    self.available_scripts = goglib_get_data.games_info(data_dir)
>   File "/home/andrew/Applications/GamesNebula/games_nebula/modules/goglib_get_data.py", line 39, in games_info
    goglib_get_banner.goglib_get_banner(banner_path_0)
>   File "/home/andrew/Applications/GamesNebula/games_nebula/modules/goglib_get_banner.py", line 30, in goglib_get_banner
    banner_url = raw_data[0]['srcset'].split('_')[0] + '.jpg'
>   File "/usr/lib/python2.7/site-packages/bs4/element.py", line 1071, in __getitem__
    return self.attrs[key]
> KeyError: 'srcset'
> [andrew@schotty-tower-wired games_nebula]$

**Comment by yancharkin** [comment]
Looks like GN fails to download an image for some game. Add:

    print(game_name)

to "/home/andrew/Applications/GamesNebula/games_nebula/modules/goglib_get_banner", line 22
After that, when running the start.sh script you should see the game's name right before the error. Tell me that name and I'll try to fix this issue.

As a temporary solution you can try to replace:

    banner_url = raw_data[0]['srcset'].split('_')[0] + '.jpg'

in the same file, line 30, to:

    banner_url = raw_data[0]['srcset']

**Comment by yancharkin** [comment]
@andrewschott Is it still an issue?

**Comment by gtxe** [comment]
Hello,
I'm new to bugreporting: is it possible to reopen the issue?
After adding `print(game_name)` the name was visible: for me it was `fatal_fury_special`
Then I created a dummy image-file: "/opt/games_nebula-master/images/goglib/fatal_fury_special.jpg"
New start: next game-name with missing image appears.
I tryed the temporary solution as you discribed.

Here is the new output:

> Authorized on GOG
final_doom_game
Traceback (most recent call last):
  File "/opt/games_nebula-master/games_nebula.py", line 6756, in <module>
    sys.exit(main())
  File "/opt/games_nebula-master/games_nebula.py", line 6752, in main
    app = GUI()
  File "/opt/games_nebula-master/games_nebula.py", line 137, in __init__
    self.create_main_window()
  File "/opt/games_nebula-master/games_nebula.py", line 336, in create_main_window
    self.create_goglib_tab_content('auto')
  File "/opt/games_nebula-master/games_nebula.py", line 525, in create_goglib_tab_content
    self.available_scripts = goglib_get_data.games_info(data_dir)
  File "/opt/games_nebula-master/modules/goglib_get_data.py", line 39, in games_info
    goglib_get_banner.goglib_get_banner(banner_path_0)
  File "/opt/games_nebula-master/modules/goglib_get_banner.py", line 30, in goglib_get_banner
    banner_url = raw_data[0]['srcset'] # banner_url = raw_data[0]['srcset'].split('_')[0] + '.jpg'
  File "/usr/lib/python3.7/site-packages/bs4/element.py", line 1071, in __getitem__
    return self.attrs[key]
KeyError: 'srcset'

**Comment by yancharkin** [comment]
@gtxe Thanks for the report. I'll take a look a bit later. Check in a day, maybe two.

**Comment by TSedlar** [comment]
Just commenting to note that I get the same error.

EDIT:

After doing your proposed changes, I get the following error:

```
Authorized on GOG
the_witcher_3_wild_hunt_game_of_the_year_edition_game
Traceback (most recent call last):
  File "/home/tyler/games_nebula/games_nebula.py", line 6756, in <module>
    sys.exit(main())
  File "/home/tyler/games_nebula/games_nebula.py", line 6752, in main
    app = GUI()
  File "/home/tyler/games_nebula/games_nebula.py", line 137, in __init__
    self.create_main_window()
  File "/home/tyler/games_nebula/games_nebula.py", line 336, in create_main_window
    self.create_goglib_tab_content('auto')
  File "/home/tyler/games_nebula/games_nebula.py", line 525, in create_goglib_tab_content
    self.available_scripts = goglib_get_data.games_info(data_dir)
  File "/home/tyler/games_nebula/modules/goglib_get_data.py", line 39, in games_info
    goglib_get_banner.goglib_get_banner(banner_path_0)
  File "/home/tyler/games_nebula/modules/goglib_get_banner.py", line 32, in goglib_get_banner
    banner_url = raw_data[0]['srcset'] # .split('_')[0] + '.jpg'
  File "/home/tyler/miniconda3/lib/python3.6/site-packages/bs4/element.py", line 1016, in __getitem__
    return self.attrs[key]
KeyError: 'srcset'
```

I included `print(repr(raw_data))` right after the initialization of the raw_data object, and get the following data:

```
[<source media="(max-width: 749px)" ng-srcset="{{tile.data.image | image:'product_tile_116_2x':'jpg'}} 2x,
            {{tile.data.image | image:'product_tile_116':'jpg'}} 1x"><source ng-srcset="{{tile.data.image | image:'product_tile_136_2x':'jpg'}} 2x,
            {{tile.data.image | image:'product_tile_136':'jpg'}} 1x"><img alt="" class="product-tile__cover-img" ng-src="{{tile.data.image | image:'product_tile_136':'jpg'}}"/></source></source>, <source ng-srcset="{{tile.data.image | image:'product_tile_136_2x':'jpg'}} 2x,
            {{tile.data.image | image:'product_tile_136':'jpg'}} 1x"><img alt="" class="product-tile__cover-img" ng-src="{{tile.data.image | image:'product_tile_136':'jpg'}}"/></source>]

```

I can confirm that this lets me launch the program:

```
banner_url = None

try:
    banner_url = raw_data[0]['srcset'].split('_')[0] + '.jpg'
except:
    banner_url = 'https://place-hold.it/518x240/000/fff.jpg&text=Placeholder'
```

As a temporary WIP fix, where banner_url is initialized.

**Comment by yancharkin** [comment]
@TSedlar I implemented something similar to your fix.
@gtxe @TSedlar Hopefully now the issue fixed. 
Here is repository for images: https://github.com/yancharkin/games_nebula_goglib_images You can add missing images yourself and then send me PR (if you like).

**Comment by gtxe** [comment]
The fix of TSedlar works, now there are black "placeholder"-images, as expected.

**Comment by yancharkin** [comment]
@gtxe Can you test my implementation? It's already in master branch.

**Comment by TSedlar** [comment]
@yancharkin I've ran it from master and it works!

**Comment by yancharkin** [comment]
@TSedlar Great! I'll try to improve my implementation and report later.

**Comment by andrewschott** [comment]
> @andrewschott Is it still an issue?

Sorry I have been out of town and then got ill upon return.  Yay winter bugs!

Anyway, I just had an opportunity to repull and retry.  Things are now working as they should for the most part.  Thanks to whomever made the commit that fixed things.   The one issue that I do have, which is not a literal game breaker, is alot of the images are just generic GOG.COM images or a black image with text overlay of the title.  Its roughly for me an even split between the asset art that is appropriate, the generic gog logo, and the black background with title text overlay.  The few titles I just tried (few dosbox and a few native) all run just fine after a download and install.

Thanks!

**Comment by gtxe** [comment]
The new master branch is working good, many thanks.

Some missing images I borrowed from GOG.
They have lower resolution (256x117 and not 518x240), but better then no pictures.
I am not familiar with git and do not know how to add files to a repository. 
So I uploaded them here: [link to some missing images](https://mega.nz/#F!j5FAHSjY!4TFPeF0hsW6zUaETDSJs0g)
You can add the files to your repo, if they are ok.

**Comment by yancharkin** [comment]
@andrewschott @gtxe Glad to hear that now it works for you.
@gtxe Thanks for the images.

When I have a chance, I'll try to implement better scraper.

**Comment by yancharkin** [comment]
@gtxe Instruction how to get high resolution image:
1. Open game page (for example https://www.gog.com/game/doom_ii_final_doom)
2. Open inspector (Firefox: Ctrl+Shift+C, Chrome: Ctrl+Shift+I)
3. Search (Ctrl+F) for "picture", first founded tag should be the right one.
4. From any "source" tag inside "picture" tag copy value of "srcset" attribute (right mouse button / Edit as HTML). In case of "doom_ii_final_doom" in will be "https://images.gog.com/429f10c7b02734605d78493f8102100794cd4dac451949dc553294478f8bed12_product_card_v2_mobile_slider_450.jpg"
5. Remove everything starting from "_product". And you'll get a link to HD image: "https://images.gog.com/429f10c7b02734605d78493f8102100794cd4dac451949dc553294478f8bed12.jpg"

**Comment by gtxe** [comment]
It works for games that are still available in the store.

But for games that are not in the store (not anymore), I found another way:
- open the library in gog
- right click on the picture of a game
- copy link of the image
  for example Interstate 76 NitroPak [https://images-3.gog.com/e1ad4255dd131400efe422579599df4206ad387f485580e0029b467d3ac372ce_196.jpg](https://images-3.gog.com/e1ad4255dd131400efe422579599df4206ad387f485580e0029b467d3ac372ce_196.jpg)
- removed _196 in the name [https://images-3.gog.com/e1ad4255dd131400efe422579599df4206ad387f485580e0029b467d3ac372ce.jpg](https://images-3.gog.com/e1ad4255dd131400efe422579599df4206ad387f485580e0029b467d3ac372ce.jpg)
- and you get a hi-res image

Images in the link above updated.

**Comment by yancharkin** [comment]
@gtxe Thanks for the info. Definitely, there is a "proper" way to get those images. When I have some free time, I'll try to find it.

**Comment by TSedlar** [comment]
@yancharkin I just looked into it a bit and I believe the best way to go about it would be this:

Parse the game ID list: https://gogapidocs.readthedocs.io/en/latest/gameslist.html

Probably fuzzy-find the game ID you're looking for, then use the GOG API (doesn't require a key for what we're trying to do)

Example ID using divinity original sin enhanced edition: 1445516929

And use the API: http://api.gog.com/products/<product id>

So in the example case: http://api.gog.com/products/1445516929

```
{
  "id": 1445516929,
  "title": "Divinity: Original Sin - Enhanced Edition",
  "purchase_link": "https://www.gog.com/checkout/manual/1445516929",
  "slug": "divinity_original_sin_enhanced_edition",
  "content_system_compatibility": {
    "windows": true,
    "osx": true,
    "linux": false
  },
  "languages": {
    "cn": "中文(简体)",
    "cz": "český",
    "de": "Deutsch",
    "en": "English",
    "es": "español",
    "fr": "français",
    "it": "italiano",
    "pl": "polski",
    "ru": "русский"
  },
  "links": {
    "purchase_link": "https://www.gog.com/checkout/manual/1445516929",
    "product_card": "http://www.gog.com/game/divinity_original_sin_enhanced_edition",
    "support": "https://www.gog.com/support/divinity_original_sin_enhanced_edition",
    "forum": "http://www.gog.com/forum/divinity_series"
  },
  "in_development": {
    "active": false,
    "until": null
  },
  "is_secret": false,
  "is_installable": true,
  "game_type": "game",
  "is_pre_order": false,
  "release_date": "2015-10-27T19:00:00+0200",
  "images": {
    "background": "//images-1.gog.com/9b0c144887009fc55957f543d7f8afede4761b65f9c82e45a89314fcf354b127.jpg",
    "logo": "//images-2.gog.com/848d214df130e1606052c2e1fda7f13199da21bf805544843ad0ff2bdfae146c_glx_logo.jpg",
    "logo2x": "//images-1.gog.com/848d214df130e1606052c2e1fda7f13199da21bf805544843ad0ff2bdfae146c_glx_logo_2x.jpg",
    "icon": "//images-1.gog.com/0542c1b78828cfb3e0be49a1ec121e9e0bb80918df57b53147e65e72e3d806ff.png",
    "sidebarIcon": "//images-2.gog.com/0542c1b78828cfb3e0be49a1ec121e9e0bb80918df57b53147e65e72e3d806ff_sbicon.png",
    "sidebarIcon2x": "//images-1.gog.com/0542c1b78828cfb3e0be49a1ec121e9e0bb80918df57b53147e65e72e3d806ff_sbicon_2x.png",
    "menuNotificationAv": "//images-3.gog.com/0542c1b78828cfb3e0be49a1ec121e9e0bb80918df57b53147e65e72e3d806ff_menu_notification_av.png",
    "menuNotificationAv2": "//images-1.gog.com/0542c1b78828cfb3e0be49a1ec121e9e0bb80918df57b53147e65e72e3d806ff_menu_notification_av2.png"
  },
  "dlcs": {
    "products": [
      {
        "id": 1445938948,
        "link": "http://api.gog.com/products/1445938948",
        "expanded_link": "http://api.gog.com/products/1445938948"
      },
      {
        "id": 1445941229,
        "link": "http://api.gog.com/products/1445941229",
        "expanded_link": "http://api.gog.com/products/1445941229"
      }
    ],
    "all_products_url": "http://api.gog.com/products?ids=1445938948%2C1445941229",
    "expanded_all_products_url": "http://api.gog.com/products?ids=1445938948%2C1445941229"
  }
}
```

The image we're going to use is `images.logo` (`//images-2.gog.com/848d214df130e1606052c2e1fda7f13199da21bf805544843ad0ff2bdfae146c_glx_logo.jpg`)

Getting the 'HD' image that we want, one would do:

```
'https:' + images.logo.split('_')[0] + '.jpg'
```

resulting in `https://images-2.gog.com/848d214df130e1606052c2e1fda7f13199da21bf805544843ad0ff2bdfae146c.jpg`

![](https://images-2.gog.com/848d214df130e1606052c2e1fda7f13199da21bf805544843ad0ff2bdfae146c.jpg)

I can try to mock up some python code that emulates this when I get a bit of time.

**Comment by TSedlar** [comment]
Another way to get the game IDs you own (if you're logged in, not sure if this is already supported in the API currently, I haven't had an in-depth look)

If you are not logged in, it redirects to: https://embed.gog.com/##openlogin

is to just read this URL: https://embed.gog.com/user/data/games

for me, the output is:

```json
{
  "owned": [
    1445516929,
    1495134320,
    1553712069,
    1801418160,
    1958228073,
    1640424747
  ]
}
```

**Comment by TSedlar** [comment]
I've made a [pyfiddle script](https://pyfiddle.io/fiddle/8e5994a3-10df-4d5c-b805-96e169c5010a/?i=true) that parses the game ID list.

It parses the game id list documentation: https://gogapidocs.readthedocs.io/en/latest/_sources/gameslist.rst.txt

And uses the above listed API.

It does not solve the issue of a game being removed, though. As they are removed from that listing. The embeded game API url in the above comment would have to be implemented for that to be supported.

**Comment by TSedlar** [comment]
The above game listing does not actually have every game (RiME was not listed), but I figured out the correct way to do this by using the [list search api](https://gogapidocs.readthedocs.io/en/latest/listing.html)

And fuzzy finding using [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) to find the most accurate matching slug.

I've made a PR with the fixes in #40, but the README will need to be updated to include the need of doing `pip install fuzzywuzzy`

It will work if people do not have fuzzywuzzy, by checking if the slug exactly equals the query (game_name.. which, it always should).

**Comment by yancharkin** [comment]
@TSedlar Thanks for your efforts, but I think there is a better way to fix this issue. You reminded me about Yepoleb's GOG API implementation, which I already use for authorization. It works reliably and doesn't add new dependencies. Could you please test and compare my solution with yours: https://github.com/yancharkin/games_nebula/tree/get_img_with_gogapi

**Comment by TSedlar** [comment]
@yancharkin My solution does work without it, the slugs should always be the same if you're pulling owned games from the API (same as the store URL), and it can be removed.

Your solution does work for me, but I do not know about games not in the store.

@gtxe will have to chime in for that.

I find it a bit weird that some images do not exist in the .games_nebula folder

![image](https://user-images.githubusercontent.com/924309/52009322-e0af0300-248f-11e9-9258-b93ea7735e83.png)

but do show up in the program

![image](https://user-images.githubusercontent.com/924309/52009349-f3293c80-248f-11e9-9236-ff089af6c12c.png)

Is this because of the [repo of images](https://github.com/yancharkin/games_nebula_goglib_images) you posted above?

**Comment by yancharkin** [comment]
@TSedlar 
> Is this because of the repo of images you posted above?

Yes, setup script download images from this repository to the application root directory, images downloaded to the .games_nebula directory only if they are missing in that location.

**Comment by TSedlar** [comment]
@yancharkin ahh gotcha well it all works as expected then :+1:

**Comment by yancharkin** [comment]
@TSedlar 
> I do not know about games not in the store.

Just tested on 'Planescape: Torment' (not 'Enhanced Edition'), works fine.

**Comment by gtxe** [comment]
> @TSedlar Thanks for your efforts, but I think there is a better way to fix this issue. You reminded me about Yepoleb's GOG API implementation, which I already use for authorization. It works reliably and doesn't add new dependencies. Could you please test and compare my solution with yours: https://github.com/yancharkin/games_nebula/tree/get_img_with_gogapi

@yancharkin: works great, no missing images  :+1: 
Thank you very much

**Comment by yancharkin** [comment]
@andrewschott Could you please test code from this branch: https://github.com/yancharkin/games_nebula/tree/get_img_with_gogapi

**Comment by andrewschott** [comment]
I am still having the issue.  I deleted and repulled too to see if there was something I jacked up, but nope.
![screenshot from 2019-01-30 16-53-47](https://user-images.githubusercontent.com/14102747/52018360-c1c06900-24af-11e9-8e67-2ec20b66f7f1.png)

**Comment by yancharkin** [comment]
@andrewschott Remove everything from _~/.games_nebula/images/goglib/_

**Comment by andrewschott** [comment]
That fixed things.  All the games on my account now have official images.  Thanks!

> [andrew@schotty-tower-wired games_nebula]$ rm -rf ~/.games_nebula/images/goglib/
> [andrew@schotty-tower-wired games_nebula]$ ./start.sh 
> Authorized on GOG
> Getting picture for: 'betrayal_at_krondor_copy3'
> Getting picture for: 'betrayal_in_antara'
> Getting picture for: 'beyond_zork_the_coconut_of_quendor'
> Getting picture for: 'champions_of_krynn'
> Getting picture for: 'curse_of_the_azure_bonds'
> Getting picture for: 'dark_queen_of_krynn_the'
> Getting picture for: 'dark_sun_shattered_lands'
> Getting picture for: 'dark_sun_wake_of_the_ravager'
> Getting picture for: 'death_knights_of_krynn'
> Getting picture for: 'drod_1_king_dugans_dungeon'
> Getting picture for: 'drod_2_journey_to_rooted_hold'
> Getting picture for: 'drod_3_the_city_beneath'
> Getting picture for: 'duke_nukem_3d_atomic_edition'
> Getting picture for: 'eye_of_the_beholder'
> Getting picture for: 'eye_of_the_beholder_ii_the_legend_of_darkmoon'
> Getting picture for: 'eye_of_the_beholder_iii_assault_on_myth_drannor'
> Getting picture for: 'forgotten_realms_unlimited_adventures'
> Getting picture for: 'gateway_to_the_savage_frontier'
> Getting picture for: 'hillsfar_copy3'
> Getting picture for: 'master_of_orion'
> Getting picture for: 'pirates'
> Getting picture for: 'planetfall'
> Getting picture for: 'pool_of_radiance'
> Getting picture for: 'pools_of_darkness'
> Getting picture for: 'ravenloft_stone_prophet'
> Getting picture for: 'ravenloft_strahds_possession'
> Getting picture for: 'secret_of_the_silver_blades'
> Getting picture for: 'treasures_of_the_savage_frontier'
> Getting picture for: 'ultima_1'
> Getting picture for: 'ultima_2'
> Getting picture for: 'ultima_3'
> Getting picture for: 'ultima_iv'
> Getting picture for: 'ultima_underworld_1'
> Getting picture for: 'ultima_underworld_2'
> Getting picture for: 'ultima_v'
> Getting picture for: 'ultima_vi'
> Getting picture for: 'zork_ii_the_wizard_of_frobozz'
> Getting picture for: 'zork_iii_the_dungeon_master'
> Getting picture for: 'zork_the_great_underground_empire'
> Getting picture for: 'zork_zero_the_revenge_of_megaboz'
> [andrew@schotty-tower-wired games_nebula]$

**Comment by yancharkin** [comment]
@andrewschott You are welcome.
Thanks to everyone for helping fix this issue (especially to @TSedlar).
