### ISSUE TITLE
Consider co-working with lutris/pol project

### ISSUE THREAD

**Issue by tkaczz** [yancharkin/games_nebula#39]
Just very much recently lutris (0.5 beta) project added support for gog platform. Maybe co-working with that project could get more benefit than splitting efforts.

I'm not a developer of that project, just linux enthusiast. 

https://www.gamingonlinux.com/articles/the-first-beta-for-lutris-05-is-out-with-a-refreshed-ui-and-gog-support.13240

**Comment by yancharkin** [comment]
I know about lutris project. Maybe I'll contribute to it at some point.
