### ISSUE TITLE
Application doesn't run on Arch

### ISSUE THREAD

**Issue by mateossh** [yancharkin/games_nebula#4]
When I tried to run application I saw python error: 
`ImportError: No module named gi`

**Comment by mateossh** [comment]
I had to install package called `python2-gobject`

**Comment by yancharkin** [comment]
Looks like I missed '2' in package name. Thanks for the report. Fixed in README.

**Comment by yancharkin** [comment]
Does it work for you now?

**Comment by mateossh** [comment]
It looks fine right now. You can close issue
