### ISSUE TITLE
UI for alternate/configuration executables

### ISSUE THREAD

**Issue by aubade** [yancharkin/games_nebula#41]
A number of games on GoG have separate configuration or alternate executables (For example, most of Falcom's Ys Games--Origin, I & II Chronicles, Oath in Felghana, Memories of Celceta, and Ark of Napishtim at least all have configuration utilities) and it'd be nice to be able to set Nebula up to be able to easily run them in the same wine prefix, or whatever other environment, as the game itself.

**Comment by yancharkin** [comment]
It's possible to point GN to the configuration utility by adding its name to [autosetup.ini](https://github.com/yancharkin/games_nebula_goglib_scripts/blob/master/autosetup.ini)

To run an executable in the same wine prefix as the main exe you have to click two buttons:
![pic0](https://user-images.githubusercontent.com/12972830/53292505-57f85e00-37d4-11e9-8aaf-02d52cfb8b8b.png)
![pic1](https://user-images.githubusercontent.com/12972830/53292510-60509900-37d4-11e9-9d86-589bd8a07591.png)

You can get access to ScummVM settings by clicking this button:
![pic3](https://user-images.githubusercontent.com/12972830/53292511-6777a700-37d4-11e9-8c76-96280e66c135.png)

DosBox games shouldn't provide some sort of menu out of the box.

I'll think about a better way to implement this feature. Can you provide a list of alternate executables for at least one game?

**Comment by aubade** [comment]
For Ys VI - The Ark of Napishtim, since it's the one inspiring the request:

ys6_win_dx9.exe
ys6_win.exe
config_dx9.exe
config.exe

(the ones without _dx9 are directx8 versions)

**Comment by yancharkin** [comment]
OK. I'll take a look when I have some time.

**Comment by yancharkin** [comment]
Done. Now you can select up to 4 alternative executables. Please test.
![pic1](https://user-images.githubusercontent.com/12972830/53302724-65642580-3872-11e9-9bae-c55b799a74d1.png)

**Comment by aubade** [comment]
It's working brilliantly for me! Thank you so much.

**Comment by yancharkin** [comment]
I'm glad to hear it.
