### ISSUE TITLE
Q: Support automatically for DLC

### ISSUE THREAD

**Issue by waltercool** [yancharkin/games_nebula#44]
Hi,

Sorry to open a so related with https://github.com/yancharkin/games_nebula/issues/21 issue, but I think my question would be different.

First of all, congratulations for your project, is amazing! Please never make webkit a full dependency :+1: 

Now, going directly to the point, there is some way to automatically support DLCs? I mean, without the custom scripts located at goglib? Maintaining per project must be quite painful and slow.

I seen my games with DLC folders downloaded, and looks like they everyone share a same behavior (Linux in my case):

/${GAME_NAME}/${GAME_NAME}_${VERSION}.sh
/${GAME_NAME}/dlc/${DLC_NAME}/${DLC_NAME}_${VERSION}.sh

I can't guarantee the format exists that way for every game, but I seen Neverwinter Nights, Stellaris, Surviving Mars and Sudden Strike using the same pattern.

Many thanks! Again, I loved your project!

**Comment by waltercool** [comment]
Something in my mind right now, could be a small interface doing: List all dlc containing a ${DLC_NAME}_${VERSION}.sh, and display ${DLC_NAME} with a install button for now.

If that format doesn't exist, skip for now.

**Comment by yancharkin** [comment]
I'll look into it.

**Comment by yancharkin** [comment]
Try ['dlc' branch](https://github.com/yancharkin/games_nebula/tree/dlc).

**Comment by waltercool** [comment]
Many thanks!

Just tried today, the new option detects new DLC, but:
- Runs DLC installer, there is some possibility to install the DLC just like games_nebula installs the main game? Should be pointing to same path
- It detects non-installable DLC, like artbook/soundtrack/others, which aren't installable.

I'm not expert with pyGTK, but let me try something from my side.

**Comment by yancharkin** [comment]
Well, it's easy to unpack DLC installer to the game directory (even fully automatically), but I'm not sure that will be enough. For example, DLC installers may have different directory structure and for Windows games, registry key often required.  I don't own any Linux games with DLC (and only one Windows game) so I can't check.
You can try to do something yourself, but GN code is a mess :)
Another way you can help, is unpack DLC installers to the relevant game directories and check if all games detect DLCs. If so, post DLC installers content.

**Comment by yancharkin** [comment]
Try ['dlc2' branch](https://github.com/yancharkin/games_nebula/tree/dlc2).

**Comment by waltercool** [comment]
Hi,

Just tried and works great for Democracy 3 and Surviving Mars. Seems like you are automatically installing DLC instead of your previous branch.

Now, I got an error with Stellaris

```
Traceback (most recent call last):
  File "games_nebula.py", line 5541, in watch_process
    self.goglib_install_dlc(game_name)
  File "games_nebula.py", line 5050, in goglib_install_dlc
    goglib_name_to_pid_install_dlc_dict[game_name], stdin, stdout, stderr = GLib.spawn_async(command,
UnboundLocalError: local variable 'command' referenced before assignment
```

**Comment by yancharkin** [comment]
Now the error should be fixed.

**Comment by waltercool** [comment]
Now it works great, just found another bug, when the game doesn't include DLC

```
Traceback (most recent call last):
  File "./games_nebula.py", line 5518, in watch_process
    self.goglib_unpack_game(game_name)
  File "./games_nebula.py", line 4987, in goglib_unpack_game
    self.dlcs_count = len(os.listdir(dlcs_dir))
FileNotFoundError: [Errno 2] No such file or directory:
```

I think adding a os.path.isdir should do it.

**Comment by yancharkin** [comment]
Fixed.

**Comment by waltercool** [comment]
I can confirm it works now!

Let me test the next days and give you any feedback I experience.

Many thanks!

**Comment by yancharkin** [comment]
I made a few more changes and merged them into the master branch.

**Comment by yancharkin** [comment]
Can you give me your feedback?
I believe that now automatic installation of DLC work both for native and windows games.

**Comment by waltercool** [comment]
Yes, it works great! Many thanks!
Closing request.
