### ISSUE TITLE
Blank GoG authorization screen with python 3 and current libraries.

### ISSUE THREAD

**Issue by clort81** [yancharkin/games_nebula#46]
Distro: devuan beowulf
gtk3 Version: 3.24.13-1
python3 Version: 3.7.5
lgogdownloader Version: 3.4
innoextract Version: 1.7-2+b1
DE: openbox
DM: none

**Bug description**
After clicking 'yes' to authorize on GOG, i get a blank screen for Games Nebula.

**Steps to reproduce the behavior**
git pull current git master, run setup.sh, do not select install inoextract, 
run games_nebula.py from build directory with:
$ python3 games_nebula.py

**Screenshots**
![delme](https://user-images.githubusercontent.com/51511737/73129727-c64c2e80-3fea-11ea-837a-8f4ac20798b9.png)

**Additional Info**
lgogdownloader --login gives me
"Couldn't resolve host name"

**Comment by yancharkin** [comment]
First of all, you certainly have an issue with lgogdownloader. Even if you'll pass the authorization window, GN will be unusable without lgogdownloader. Try to update it to the latest version.

As for the black screen, it could be an issue with the graphics driver or with gir1.2-webkit2-4.0 package, try clicking on the black window with the right mouse button and select "Reload" in the menu. If it won't help post console output here.

**Comment by yancharkin** [comment]
@clort81 Is it still an issue?

**Comment by yancharkin** [comment]
@clort81 No response, closing.
Please, do not open an issue if you're not ready to cooperate, it takes time (in some cases a lot of time) to investigate what can cause the problem.
