### ISSUE TITLE
Authorization always fails.

### ISSUE THREAD

**Issue by zilti** [yancharkin/games_nebula#5]
Like the title says: it always fails.

**Comment by yancharkin** [comment]
Currently **Games Nebula** uses [lgogdownloader](https://github.com/Sude-/lgogdownloader). So if you have problems with authorization try to log in with **lgogdownloader** directly, maybe you need to enter security code or export cookies. **Games Nebula** can help you wIth exporting cookies: if you open **GOG.COM** tab and authorize there, cookies will be saved to **~/.config/lgogdownloader/cookies.txt** (that's what you need).

**Comment by yancharkin** [comment]
No comments in a few days, so I assume, this issue resolved. But to be clear, it's not a bug, it's a limitation that you have to deal with.
